name: reaktoro-env
channels:
  - conda-forge
dependencies:
  - reaktoro
  - jupyter
  - widgetsnbextension
  - jupyter_contrib_nbextensions
  - nb_conda
  - numpy
  - scipy
  - pandas
  - matplotlib-base

environment:
  DATABASES: {{ root }}/databases
  MATPLOTLIBRC: {{ root }}/config
